include $(PROJ_HOME)/build/option.mak
OBJDIR=./
MODULE_NAME = $(PARAM)
LIB_RESULE=$(MODULE_NAME).a

S1 := $(wildcard *.c)
SOURCE:=$(S1)

LOCAL_INCLUDE := -I./

include $(PROJ_HOME)/build/app_build.mak
